In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('http://bit.ly/imdbratings')
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [4]:
#method first

filter1= movies['duration']>=200

In [6]:
movies[filter1]  # rows will appear with >=200 duration only

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."

In [9]:
#we can use condition directly also, which is nothing act like boolean

movies[movies.duration>=200]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."

In [11]:
#and we want to see any see any specific column with that filtered condition

movies[movies.duration>=200]['title']

2                             The Godfather: Part II
7      The Lord of the Rings: The Return of the King
17                                     Seven Samurai
78                       Once Upon a Time in America
85                                Lawrence of Arabia
142                Lagaan: Once Upon a Time in India
157                               Gone with the Wind
204                                          Ben-Hur
445                             The Ten Commandments
476                                           Hamlet
630                                        Malcolm X
767                  It's a Mad, Mad, Mad, Mad World
Name: title, dtype: object

In [12]:
#we do have best method than above one which we going to discuss below

# How do I apply multiple filter criteria to a pandas DataFrame?

In [13]:
# simply we can use '&' = 'and' or '|'= 'OR' condition

In [21]:
movies[(movies['duration']>=200) & (movies['genre']=='Action')] #and condition

#Note: we need to use '&' or pipe('|') , here 'and' and 'or' will not work

,star_rating,title,content_rating,genre,duration,actors_list
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."

In [22]:
movies[(movies['duration']>=200) | (movies['genre']=='Action')] # or condition

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
...,...,...,...,...,...,...
918,7.5,Running Scared,R,Action,122,"[u'Paul Walker', u'Cameron Bright', u'Chazz Pa..."
954,7.4,X-Men,PG-13,Action,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."
963,7.4,La Femme Nikita,R,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."

In [24]:
#another method which is equivalent to 'OR' condition

movies[movies['genre'].isin(['Action','Crime'])]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
963,7.4,La Femme Nikita,R,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [30]:
#Best method to check columns with filter condition

movies.loc[(movies['duration']>200)&(movies['genre']=='Drama'),'star_rating':'genre']

     star_rating               title content_rating  genre
17           8.7       Seven Samurai        UNRATED  Drama
157          8.2  Gone with the Wind              G  Drama
476          7.8              Hamlet          PG-13  Drama

In [46]:
#not in filter

movies.loc[~(movies['duration']>=100)& ~(movies['genre'].isin(['Drama','Crime','Action','Comedy'])),'star_rating':'duration']

,star_rating,title,content_rating,genre,duration
55,8.5,The Lion King,G,Animation,89
61,8.5,Grave of the Fireflies,UNRATED,Animation,89
64,8.4,WALL-E,G,Animation,98
101,8.3,Monty Python and the Holy Grail,PG,Adventure,91
105,8.3,The Third Man,NOT RATED,Film-Noir,93
...,...,...,...,...,...
903,7.5,Heavenly Creatures,R,Biography,99
913,7.5,Suspiria,X,Horror,92
938,7.4,Alice in Wonderland,G,Animation,75
943,7.4,The Bucket List,PG-13,Adventure,97
966,7.4,The Simpsons Movie,PG-13,Animation,87

In [53]:
#kind of regular expression filter
movies[movies['title'].str.contains('Man',na=False)]

,star_rating,title,content_rating,genre,duration,actors_list
105,8.3,The Third Man,NOT RATED,Film-Noir,93,"[u'Orson Welles', u'Joseph Cotten', u'Alida Va..."
148,8.2,The Elephant Man,PG,Biography,124,"[u'Anthony Hopkins', u'John Hurt', u'Anne Banc..."
235,8.1,Yip Man,R,Action,106,"[u'Donnie Yen', u'Simon Yam', u'Siu-Wong Fan']"
251,8.1,The Man Who Shot Liberty Valance,APPROVED,Drama,123,"[u'James Stewart', u'John Wayne', u'Vera Miles']"
292,8.1,The Manchurian Candidate,APPROVED,Mystery,126,"[u'Frank Sinatra', u'Laurence Harvey', u'Janet..."
319,8.0,Manhattan,R,Comedy,96,"[u'Woody Allen', u'Diane Keaton', u'Mariel Hem..."
325,8.0,Rain Man,R,Drama,133,"[u'Dustin Hoffman', u'Tom Cruise', u'Valeria G..."
341,8.0,Cinderella Man,PG-13,Biography,144,"[u'Russell Crowe', u'Ren\xe9e Zellweger', u'Cr..."
345,8.0,No Man's Land,R,Drama,98,"[u'Branko Djuric', u'Rene Bitorajac', u'Filip ..."
420,7.9,The Man Who Would Be King,PG,Action,129,"[u'Sean Connery', u'Michael Caine', u'Christop..."
434,7.9,Iron Man,PG-13,Action,126,"[u'Robert Downey Jr.', u'Gwyneth Paltrow', u'T..."
452,7.9,The Man from Nowhere,R,Action,119,"[u'Bin Won', u'Sae-ron Kim', u'Tae-hoon Kim']"
581,7.8,Man on Fire,R,Action,146,"[u'Denzel Washington', u'Christopher Walken', ..."
594,7.7,Dead Man,R,Drama,121,"[u'Johnny Depp', u'Gary Farmer', u'Crispin Glo..."
688,7.7,The Wicker Man,R,Horror,88,"[u'Edward Woodward', u'Christopher Lee', u'Dia..."
697,7.7,Inside Man,R,Crime,129,"[u'Denzel Washington', u'Clive Owen', u'Jodie ..."
715,7.6,Man Bites Dog,NC-17,Comedy,95,"[u'Beno\xeet Poelvoorde', u'Jacqueline Poelvoo..."
746,7.6,The Man Who Wasn't There,R,Crime,116,"[u'Billy Bob Thornton', u'Frances McDormand', ..."
765,7.6,Ip Man 2,R,Action,108,"[u'Donnie Yen', u'Xiaoming Huang', u'Sammo Kam..."
774,7.6,A Single Man,R,Drama,99,"[u'Colin Firth', u'Julianne Moore', u'Matthew ..."
784,7.6,Dead Man Walking,R,Crime,122,"[u'Susan Sarandon', u'Sean Penn', u'Robert Pro..."
843,7.5,Marathon Man,R,Crime,125,"[u'Dustin Hoffman', u'Laurence Olivier', u'Roy..."
848,7.5,The Man Who Knew Too Much,PG,Thriller,120,"[u'James Stewart', u'Doris Day', u'Brenda de B..."
930,7.4,Man on the Moon,R,Biography,118,"[u'Jim Carrey', u'Danny DeVito', u'Gerry Becker']"
956,7.4,Manhattan Murder Mystery,PG,Comedy,104,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']"