In [1]:
import pandas as pd

In [4]:
movie = pd.read_csv('http://bit.ly/imdbratings')

movie.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [8]:
movie.shape

(979, 6)

In [11]:
movie.index   # this will give us the index value range

RangeIndex(start=0, stop=979, step=1)

In [12]:
movie.columns   # to get columns names, remember columns are not part of dateset

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [14]:
#to get range of columns

movie.loc[10:15]   # to get specfic range of rows by index

,star_rating,title,content_rating,genre,duration,actors_list
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
13,8.8,Forrest Gump,PG-13,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
14,8.8,The Lord of the Rings: The Two Towers,PG-13,Adventure,179,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort..."
15,8.7,Interstellar,PG-13,Adventure,169,"[u'Matthew McConaughey', u'Anne Hathaway', u'J..."

In [15]:
#if we don't like numerical index we can set it to other column as well as per our convenience



movie.set_index('genre',inplace=True)

In [17]:
movie.head()  # we can see that now genre is set as index now

,star_rating,title,content_rating,duration,actors_list
genre,,,,,
Crime,9.3,The Shawshank Redemption,R,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
Crime,9.2,The Godfather,R,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
Crime,9.1,The Godfather: Part II,R,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
Crime,8.9,Pulp Fiction,R,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [19]:
 movie.loc['Action']  # only rows will come with index as 'Action'

,star_rating,title,content_rating,duration,actors_list
genre,,,,,
Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
Action,8.8,Inception,PG-13,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
Action,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
Action,8.7,Star Wars,PG,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
Action,8.7,The Matrix,R,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
...,...,...,...,...,...
Action,7.5,Running Scared,R,122,"[u'Paul Walker', u'Cameron Bright', u'Chazz Pa..."
Action,7.4,X-Men,PG-13,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."
Action,7.4,La Femme Nikita,R,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
Action,7.4,The Rock,R,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
Action,7.4,Master and Commander: The Far Side of the World,PG-13,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."

In [21]:
# we can reset are index too if want to change it later back to original

movie.reset_index(inplace=True)

In [22]:
movie.head()

,genre,star_rating,title,content_rating,duration,actors_list
0,Crime,9.3,The Shawshank Redemption,R,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,Crime,9.2,The Godfather,R,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,Crime,9.1,The Godfather: Part II,R,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,Crime,8.9,Pulp Fiction,R,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [25]:
movie.index # now index are back to orignal

RangeIndex(start=0, stop=979, step=1)

In [26]:
movie.columns

Index(['genre', 'star_rating', 'title', 'content_rating', 'duration',
       'actors_list'],
      dtype='object')

In [28]:
movie.index.name ='Sr. No.'
movie.head()

,genre,star_rating,title,content_rating,duration,actors_list
Sr. No.,,,,,,
0,Crime,9.3,The Shawshank Redemption,R,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,Crime,9.2,The Godfather,R,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,Crime,9.1,The Godfather: Part II,R,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,Crime,8.9,Pulp Fiction,R,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [30]:
# you can see that now is appear to the index column, we can give any name

#we don't want index name we can remove it too

movie.index.name = None
movie.head(10)

,genre,star_rating,title,content_rating,duration,actors_list
0,Crime,9.3,The Shawshank Redemption,R,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,Crime,9.2,The Godfather,R,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,Crime,9.1,The Godfather: Part II,R,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,Crime,8.9,Pulp Fiction,R,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,Drama,8.9,12 Angry Men,NOT RATED,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
6,Western,8.9,"The Good, the Bad and the Ugly",NOT RATED,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
7,Adventure,8.9,The Lord of the Rings: The Return of the King,PG-13,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,Biography,8.9,Schindler's List,R,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
9,Drama,8.9,Fight Club,R,139,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh..."

In [32]:
#we can sort index in acending or decending, its already in acending lets try with decending

movie.sort_index(ascending = False)

,genre,star_rating,title,content_rating,duration,actors_list
978,Crime,7.4,Wall Street,R,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."
977,Horror,7.4,Poltergeist,PG,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
976,Action,7.4,Master and Commander: The Far Side of the World,PG-13,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
975,Adventure,7.4,Back to the Future Part III,PG,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
974,Comedy,7.4,Tootsie,PG,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
...,...,...,...,...,...,...
4,Crime,8.9,Pulp Fiction,R,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
3,Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
2,Crime,9.1,The Godfather: Part II,R,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
1,Crime,9.2,The Godfather,R,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
0,Crime,9.3,The Shawshank Redemption,R,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."